// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	user "byteDemo/kitex_gen/user"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CreatUser": kitex.NewMethodInfo(creatUserHandler, newUserServiceCreatUserArgs, newUserServiceCreatUserResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func creatUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCreatUserArgs)
	realResult := result.(*user.UserServiceCreatUserResult)
	success, err := handler.(user.UserService).CreatUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCreatUserArgs() interface{} {
	return user.NewUserServiceCreatUserArgs()
}

func newUserServiceCreatUserResult() interface{} {
	return user.NewUserServiceCreatUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreatUser(ctx context.Context, req *user.Req) (r *user.Resp, err error) {
	var _args user.UserServiceCreatUserArgs
	_args.Req = req
	var _result user.UserServiceCreatUserResult
	if err = p.c.Call(ctx, "CreatUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
