// Code generated by hertz generator.

package main

import (
	"byteDemo/cmd/api/biz/rpc"
	"byteDemo/cmd/user/conf"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {

	conf.Init() //启动我们的api服务配置
	rpc.Init()

	h := server.Default()

	register(h)
	h.Spin()
}
