// Code generated by hertz generator.

package api

import (
	"byteDemo/cmd/api/biz/rpc"
	"byteDemo/kitex_gen/user"
	"context"

	api "byteDemo/cmd/api/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreatUser .
// @router /user [GET]
func CreatUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.Req
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.Resp)

	//todo begin
	uResp, err := rpc.CreatUser(ctx, &user.Req{
		Id:   req.ID,
		Name: req.Name,
	}) // 远程调用user服务

	if err != nil || uResp.Code != 200 {
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp.Code = uResp.Code
	resp.Msg = uResp.Msg
	//todo end

	c.JSON(consts.StatusOK, resp)
}
